name: thinknotestudioapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.8.0
  onesignal_flutter: ^5.0.0
  table_calendar: ^3.0.9
  flutter_slidable: ^3.1.0
  shimmer: ^3.0.0
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8
  floaty_navy_bar: ^1.0.5
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ðŸ”¥ APP ICON CONFIG (ROOT LEVEL â€“ Ã‡OK Ã–NEMLÄ°)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/a.png

  # Android adaptive icon (Ã¶nerilir)

  

flutter:
  uses-material-design: true

  assets:
    - assets/
